'use client';
import React, { useState } from 'react';
import Link from 'next/link';

type Operator = { name: string; role: string; tenant_id: string };
type Case = { id: string; title: string; category: string; status: string; authority_status: string; actionability: string };
const api = process.env.NEXT_PUBLIC_FOUNDATION_API_URL || 'http://127.0.0.1:8000/api/v2';

export default function Workspace() {
  const [token, setToken] = useState('');
  const [operator, setOperator] = useState<Operator | null>(null);
  const [cases, setCases] = useState<Case[]>([]);
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState('IMPERSONATION');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  async function request(path: string, init?: RequestInit) {
    const response = await fetch(api + path, { ...init, cache: 'no-store', headers: {
      'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...init?.headers,
    }});
    if (!response.ok) {
      if (response.status === 401) { setOperator(null); setCases([]); }
      throw new Error(response.status === 401 ? 'Credential expired or invalid. Obtain a new local operator credential.' :
        response.status === 403 ? 'Your role does not allow this action.' : `Request failed (${response.status}). No change was confirmed.`);
    }
    return response.status === 204 ? null : response.json();
  }

  async function connect(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError(''); setOperator(null); setCases([]);
    try {
      const user = await request('/me');
      const rows = await request('/cases');
      setOperator(user); setCases(rows);
    } catch (e) { setError(e instanceof Error ? e.message : 'The API is unavailable.'); }
    finally { setBusy(false); }
  }

  async function createCase(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError('');
    try {
      const created = await request('/cases', { method: 'POST', body: JSON.stringify({ title, category }) });
      setCases(rows => [created, ...rows].slice(0, 50)); setTitle('');
    } catch (e) { setError(e instanceof Error ? e.message : 'Case creation failed.'); }
    finally { setBusy(false); }
  }

  async function signOut() {
    setBusy(true); setError('');
    try { await request('/credentials/revoke-all', { method: 'POST' }); setToken(''); setOperator(null); setCases([]); }
    catch (e) { setError(e instanceof Error ? e.message : 'Revocation failed.'); }
    finally { setBusy(false); }
  }

  const field = 'w-full rounded-lg border border-slate-600 bg-slate-900 p-3 text-white';
  return <main className="max-w-5xl mx-auto px-6 py-12 space-y-8">
    <header className="flex flex-wrap justify-between items-start gap-4">
      <div><p className="text-cyan-400 text-sm tracking-widest">SENTINEL</p><h1 className="text-3xl font-bold mt-2">Incident workspace</h1></div>
      <Link href="/" className="text-sm text-slate-300 underline">View legacy demonstration</Link>
    </header>
    <p className="rounded-xl border border-cyan-800 bg-cyan-950/30 p-4 text-sm text-slate-200">
      Development foundation. Cases persist in your organization’s workspace. Authority review, evidence capture,
      matching and external actions are still being implemented. Use synthetic case descriptions here.
    </p>
    {error && <p role="alert" className="border border-red-500 bg-red-950/40 p-4 rounded-lg">{error}</p>}
    {!operator ? <form onSubmit={connect} className="glass-card p-6 space-y-4 max-w-xl">
      <h2 className="text-xl font-semibold">Connect as a local operator</h2>
      <p className="text-sm text-slate-300">Enter the 8-hour credential generated by the local provisioning command. It is kept in this page’s memory and cleared when you reload.</p>
      <label className="block" htmlFor="operator-token">Operator credential</label>
      <input id="operator-token" type="password" autoComplete="off" required value={token} onChange={e => setToken(e.target.value.trim())} className={field} />
      <button disabled={busy} className="bg-cyan-600 rounded-lg px-5 py-3 font-semibold disabled:opacity-50">{busy ? 'Connecting…' : 'Connect'}</button>
      <p className="text-sm text-slate-400">See docs/SENTINEL_FOUNDATION_CHECKPOINT.md for local setup and provisioning.</p>
    </form> : <>
      <section className="flex justify-between flex-wrap gap-4 border-b border-slate-700 pb-5">
        <div><h2 className="font-semibold">{operator.name}</h2><p className="text-sm text-slate-400">{operator.role} · Organization {operator.tenant_id}</p></div>
        <button disabled={busy} onClick={signOut} className="border border-slate-600 rounded-lg px-4 py-2 disabled:opacity-50">Revoke my credentials and sign out</button>
      </section>
      {operator.role !== 'VIEWER' && <form onSubmit={createCase} className="glass-card p-6 space-y-4">
        <h2 className="text-xl font-semibold">Create a provisional incident</h2>
        <label htmlFor="case-title" className="block">Case title</label>
        <input id="case-title" required minLength={3} maxLength={200} value={title} onChange={e => setTitle(e.target.value)} className={field} />
        <label htmlFor="category" className="block">Category for review</label>
        <select id="category" value={category} onChange={e => setCategory(e.target.value)} className={field}>
          <option value="IMPERSONATION">Impersonation</option><option value="HARASSMENT">Harassment</option>
          <option value="COPYRIGHT">Copyright</option><option value="OTHER">Other</option>
        </select>
        <p className="text-sm text-slate-400">Creating a case does not establish authority, confirm a violation, or submit a report.</p>
        <button disabled={busy || title.trim().length < 3} className="bg-cyan-600 rounded-lg px-5 py-3 font-semibold disabled:opacity-50">Create case</button>
      </form>}
      <section className="space-y-4"><h2 className="text-xl font-semibold">Recent cases (up to 50)</h2>
        {!cases.length && <p className="text-slate-400">No cases have been created for your organization.</p>}
        {cases.map(row => <article key={row.id} className="glass-card p-5 space-y-2">
          <h3 className="text-lg font-semibold">{row.title}</h3>
          <p className="text-cyan-300 text-sm">{row.category} · {row.status}</p>
          <p className="text-sm text-slate-300">Authority: {row.authority_status} · Action basis: {row.actionability}</p>
          <p className="text-xs text-slate-500 break-all">{row.id}</p>
        </article>)}
      </section>
    </>}
  </main>;
}
